echo "                                                                             "
echo "           ______  __                     ______                             "
echo "          /\__  _\/\ \                   /\  _  \                            "
echo "          \/_/\ \/\ \ \___     ___   _ __\ \ \L\ \   __  _    __             "
echo "             \ \ \ \ \  _  \  / __ \/\  __\ \  __ \ /\ \/ \ / __ \           "
echo "              \ \ \ \ \ \ \ \/\ \L\ \ \ \/ \ \ \/\ \  /   //\  __/           "
echo "               \ \_\ \ \_\ \_\ \____/\ \_\  \ \_\ \_\/\_/\_\ \____\          "
echo "                \/_/  \/_/\/_/\/___/  \/_/   \/_/\/_/\//\/_/\/____/          "
echo "                                                                             "
echo "     Use Thor's Axe to cut exons into their evolutionary building blocks     "
echo "                                                                             "
